spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:./cartapplication
    username: sa
    password:
    driverClassName: org.h2.Driver